module.exports = {
  PARAM_MISSING: 422,
  PARAM_MISSING_MSG: 'Require parameter missing',
  NO_DATA: 400,
  INVALID_REQUEST: 'Invalid request',
  NO_DATA_FOUND: 'No data found',
  NO_USER_FOUND: 'User not found',
  INVALID_USER: 'Not a valid user',
  USER_ALREADY_EXIST: 'User already exist with mobile or email',
  INVALID_CATEGORY: 'Please select a valid category',
  INVALID_PRODUCT: 'Please select a valid product',
  PRODUCT_NOT_FOUND: 'Product not found',
  PRODUCT_NOT_ACCEPTED: 'You are not allowed to access this, Product bid is still in pending state',
  PRODUCT_NOT_PICKED: 'You can not make a payment, Product has not been picked yet.',
  PICKED_UP_NOT_ESTIMATED: 'You can not picked up the order without estimating the pickup date.',
  BID_NOT_FOUND: 'Bid not found',
  BID_NOT_ALLOWED: 'You are not allowed to edit this bid',
  SUCCESS: 200,
  SUCCESS_MSG: 'Success',
  QUERY_ERROR: 500,
  QUERY_ERROR_MSG: 'Something Went wrong',
  INVALID_CREDENTIAL: 401,
  INVALID_CREDENTIAL_MSG: 'Invalid credential. Please try again.',
  UNAUTHORIZE: 401,
  UNAUTHORIZE_MSG: 'Unauthorize User',
  BAD_REQUEST: 400,
  BAD_REQUEST_MSG: 'Entered data is Invalid',
  INCORRECT_EMAIL: 'Incorrect email',
  INCORRECT_PASSWORD: 'Incorrect current password',
  INCORRECT_MOBILE: 'Incorrect mobile',
  INCORRECT_OTP: 'Incorrect otp',
  OTP_EXPIRED: 'Otp has been expired',
  OTP_SENT: 'Otp has been sent to your registered number',
  BLOCKED: 'Your account has been blocked, Please contact to admin',
  MOBILE_EXIST: 'This mobile number is already registered with different user',
};
